### ISSUE TITLE
Why do you reassign view model onResume()?

### ISSUE THREAD

**Issue by bnvinay92** [kickstarter/android-oss#45]
Trying to understand the purpose of the following code in the onResume() function of your BaseActivity:

```
assignViewModel(null);
    if (viewModel != null) {
      viewModel.onResume(this);
    }
```

In which scenario(s) does viewModel end up being null here?

And isn't the null check right after reassigning viewModel a little too defensive?

**Comment by tmtron** [comment]
[`assignViewModel()`](https://github.com/kickstarter/android-oss/blob/a0ade58c74eddc03f3e83d200c1704fc882eec6f/app/src/main/java/com/kickstarter/libs/BaseActivity.java#L260) will only assign the `viewModel`, when the class uses the `@RequiresActivityViewModel` annotation. Otherwise `viewModel` may remain `null`.
