### ISSUE TITLE
proguard file?

### ISSUE THREAD

**Issue by vipulasri** [kickstarter/android-oss#46]
I don't find your proguard file. I am to know curious what all proguard rules did you write in proguard in order to achieve the apk size of around 4MB.

**Comment by christopherwright** [comment]
Hi Vipul – we aren't using Proguard so there's nothing special happening here! We tried not to include many rasterized images in the app so that's probably helped us keep the size down.

We're past the 64k method limit too so our code size is fairly large – makes me think that code shrinking might not be the most important tool in keeping APK size low.
