### ISSUE TITLE
Toolbar shadow disappears sometimes

### ISSUE THREAD

**Issue by AllanWang** [kickstarter/android-oss#65]
If you scroll very quickly and very far down, the shadow will disappear. Scrolling back up will make it appear again. Is this intended behaviour?

**Comment by luoser** [comment]
Ah, a subtle catch--looks like this is because the sort tab [inherits its 4dp elevation from its parent CoordinatorLayout](https://github.com/kickstarter/android-oss/blob/master/app/src/main/res/layout/discovery_layout.xml#L33) while the discovery toolbar (the navy blue) has [no elevation](https://github.com/kickstarter/android-oss/blob/master/app/src/main/res/layout/discovery_toolbar.xml#L11) since we would not want the top toolbar's shadow to render onto the sort tab bar. 

If you've got a suggestion for how to render this shadow only when the tab layout is hidden we'd welcome a PR!
